services:
  demo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_HTTP_PORT: 8080
      ASPNETCORE_Kestrel__Certificates__Default__Password: "291103"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
    ports:
      - "8080:8080"
      # - "8081:8081"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
    restart: always
